// Generates a Supabase seed migration for `machine_catalog` from the
// existing static catalog (packages/core/src/data/machine-catalog.ts).
// Prints SQL to stdout:
//
//   bun scripts/seed-machine-catalog.ts > supabase/migrations/<ts>_seed_machine_catalog.sql
//
// Deterministic: each row's id is derived from its static `key` (sha1, same
// shape as scripts/import-free-exercise-db.ts's idFor), so re-running is
// idempotent (`on conflict (id) do nothing`) even if the static catalog gains
// rows later. owner_id null = global seed row (docs/DECISIONS.md).
import { createHash } from "node:crypto";
import { MACHINE_CATALOG } from "../packages/core/src/data/machine-catalog";

const ID_PREFIX = "00000000-0000-4000-9100-"; // distinct block: 8000 = curated seeds, 9000 = free-exercise-db
const SOURCE_NOTE = "migrated from static catalog 2026-08-07";
const BATCH = 50;

function idFor(key: string): string {
  const hex = createHash("sha1").update(key).digest("hex").slice(0, 12);
  return ID_PREFIX + hex;
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const TS = "(extract(epoch from now()) * 1000)::bigint";

function rowSql(m: (typeof MACHINE_CATALOG)[number]): string {
  const cols = [
    sqlStr(idFor(m.key)),
    TS,
    TS,
    "null", // owner_id: global seed row
    sqlStr(m.brand),
    sqlStr(m.model),
    sqlStr(m.category),
    sqlStr(SOURCE_NOTE),
  ];
  return `  (${cols.join(", ")})`;
}

// Guard: derived ids must be unique (48-bit slug hash — collision would
// silently drop a row under `on conflict do nothing`).
const seen = new Set<string>();
for (const m of MACHINE_CATALOG) {
  const id = idFor(m.key);
  if (seen.has(id)) throw new Error(`id collision for key "${m.key}" (${id})`);
  seen.add(id);
}

const out: string[] = [];
out.push(
  "-- Seed machine_catalog from the existing static catalog",
  "-- (packages/core/src/data/machine-catalog.ts), Tier 1 brands only",
  "-- (docs/DECISIONS.md 2026-08-07).",
  "-- Generated by scripts/seed-machine-catalog.ts — do not edit by hand.",
  `-- ${MACHINE_CATALOG.length} rows. owner_id null = global seed row.`,
  "",
);

const columns =
  'insert into "machine_catalog" (id, created_at, updated_at, owner_id, brand, model, category, source_note)';
for (let i = 0; i < MACHINE_CATALOG.length; i += BATCH) {
  const values = MACHINE_CATALOG.slice(i, i + BATCH)
    .map(rowSql)
    .join(",\n");
  out.push(columns, "values", `${values}\non conflict (id) do nothing;`, "");
}

process.stdout.write(out.join("\n"));
