// Pure SQL-generation logic, split out from generate-migration.ts's CLI
// entry point so it's importable by tests without executing that file's
// CLI body (this repo's scripts run their CLI unconditionally at module
// bottom — see import-free-exercise-db.ts).
import { createHash } from "node:crypto";
import type { StagingMachine } from "./types";

export const ID_PREFIX = "00000000-0000-4000-9a00-"; // distinct block, doesn't collide with exercises' 9000 block
export const BATCH = 50;

export function idFor(brand: string, model: string): string {
  const hex = createHash("sha1")
    .update(`${brand.toLowerCase()}::${model.toLowerCase()}`)
    .digest("hex")
    .slice(0, 12);
  return ID_PREFIX + hex;
}

export function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

export function sqlJson(value: unknown): string {
  return `${sqlStr(JSON.stringify(value))}::jsonb`;
}

export const TS = "(extract(epoch from now()) * 1000)::bigint";

export function rowSql(m: StagingMachine): string {
  const cols = [
    sqlStr(idFor(m.brand, m.model)),
    TS,
    TS,
    "null", // owner_id: global seed row
    sqlStr(m.brand),
    sqlStr(m.model),
    m.aliases ? sqlJson(m.aliases) : "null",
    sqlStr(m.category),
    m.mechanism ? sqlStr(m.mechanism) : "null",
    m.muscleTargets ? sqlJson(m.muscleTargets) : "null",
    m.weightStackKg == null ? "null" : String(m.weightStackKg),
    m.plateCapacityKg == null ? "null" : String(m.plateCapacityKg),
    m.dimensions ? sqlJson(m.dimensions) : "null",
    m.productUrl ? sqlStr(m.productUrl) : "null",
    m.introducedYear == null ? "null" : String(m.introducedYear),
    m.discontinuedYear == null ? "null" : String(m.discontinuedYear),
    sqlStr(m.sourceUrl),
    m.sourceNote ? sqlStr(m.sourceNote) : "null",
  ];
  return `  (${cols.join(", ")})`;
}

export const COLUMNS =
  'insert into "machine_catalog" (id, created_at, updated_at, owner_id, brand, model, aliases, category, mechanism, muscle_targets, weight_stack_kg, plate_capacity_kg, dimensions, product_url, introduced_year, discontinued_year, source_url, source_note)';

export function generateSql(
  brandKey: string,
  machines: StagingMachine[],
): string {
  // Guard: derived ids must be unique within the batch (a hash collision, or
  // two rows genuinely sharing brand+model after normalization, would
  // silently drop a row under `on conflict do nothing`) — surfaced here so
  // it's caught before the SQL ships, not discovered as a missing row later.
  const seen = new Set<string>();
  for (const m of machines) {
    const id = idFor(m.brand, m.model);
    if (seen.has(id)) {
      throw new Error(
        `id collision for "${m.brand} ${m.model}" (${id}) — check for an unresolved duplicate`,
      );
    }
    seen.add(id);
  }

  const out: string[] = [
    `-- Seed machine_catalog rows for ${brandKey}, generated by scripts/machine-catalog/generate-migration.ts.`,
    "-- Do not edit by hand — re-run the pipeline and regenerate instead.",
    `-- ${machines.length} rows. owner_id null = global seed row (mirrors supabase/migrations/20260715055811_seed_free_exercise_db.sql).`,
    "",
  ];
  for (let i = 0; i < machines.length; i += BATCH) {
    const values = machines
      .slice(i, i + BATCH)
      .map(rowSql)
      .join(",\n");
    out.push(COLUMNS, "values", `${values}\non conflict (id) do nothing;`, "");
  }
  return out.join("\n");
}
